/**
 * Gallery project data.
 * File path: /content/projects.ts
 *
 * 24 projects spread across:
 *   - 6 product categories (PVC, polyester, acoustic, LED, photoprint, prefab) — ~4 per category
 *   - Multiple cities (Warszawa most represented, then Kraków/Wrocław/etc.)
 *   - Multiple space types (salon, łazienka, biuro, gastronomia, etc.)
 *
 * Adding a project: one entry here, no code changes needed.
 *
 * Photo URLs currently point to Unsplash placeholders matched contextually
 * to each project's space type. Swap to /images/gallery/{slug}.jpg once
 * real project photography is available.
 */

import type { Project } from "@/types";

export const projects: Project[] = [
  // ════════════════════════════════════════════════════════════
  // PVC projects
  // ════════════════════════════════════════════════════════════
  {
    slug: "lazienka-warszawa-mokotow-pvc",
    title: "Łazienka w apartamencie",
    citySlug: "warszawa",
    city: "Warszawa",
    district: "Mokotów",
    productCategory: "sufit-pvc",
    productLabel: "Sufit PVC",
    spaceType: "lazienka",
    spaceLabel: "Łazienka",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
    imageAlt: "Łazienka z lakierowanym sufitem PVC w apartamencie na Mokotowie, Warszawa",
    surfaceArea: 8,
    year: 2025,
  },
  {
    slug: "kuchnia-krakow-podgorze-pvc",
    title: "Kuchnia w lofcie",
    citySlug: "krakow",
    city: "Kraków",
    district: "Podgórze",
    productCategory: "sufit-pvc",
    productLabel: "Sufit PVC",
    spaceType: "kuchnia",
    spaceLabel: "Kuchnia",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80",
    imageAlt: "Kuchnia z białym matowym sufitem PVC w lofcie na Podgórzu, Kraków",
    surfaceArea: 18,
    year: 2025,
  },
  {
    slug: "salon-katowice-pvc-lakier",
    title: "Salon z efektem lakierowym",
    citySlug: "katowice",
    city: "Katowice",
    productCategory: "sufit-pvc",
    productLabel: "Sufit PVC",
    spaceType: "salon",
    spaceLabel: "Salon",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80",
    imageAlt: "Salon z lakierowanym sufitem PVC odbijającym światło, Katowice",
    surfaceArea: 38,
    year: 2024,
  },
  {
    slug: "lazienka-gdansk-pvc-mat",
    title: "Łazienka master",
    citySlug: "gdansk",
    city: "Gdańsk",
    productCategory: "sufit-pvc",
    productLabel: "Sufit PVC",
    spaceType: "lazienka",
    spaceLabel: "Łazienka",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200&q=80",
    imageAlt: "Łazienka master z matowym sufitem PVC, Gdańsk",
    surfaceArea: 12,
    year: 2025,
  },

  // ════════════════════════════════════════════════════════════
  // Polyester projects
  // ════════════════════════════════════════════════════════════
  {
    slug: "salon-warszawa-wilanow-poliester",
    title: "Salon w apartamentowcu",
    citySlug: "warszawa",
    city: "Warszawa",
    district: "Wilanów",
    productCategory: "sufit-poliestrowy",
    productLabel: "Sufit poliestrowy",
    spaceType: "salon",
    spaceLabel: "Salon",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    imageAlt: "Salon z matowym poliestrowym sufitem napinanym, Wilanów, Warszawa",
    surfaceArea: 45,
    year: 2025,
  },
  {
    slug: "sypialnia-wroclaw-krzyki-poliester",
    title: "Sypialnia w apartamencie",
    citySlug: "wroclaw",
    city: "Wrocław",
    district: "Krzyki",
    productCategory: "sufit-poliestrowy",
    productLabel: "Sufit poliestrowy",
    spaceType: "sypialnia",
    spaceLabel: "Sypialnia",
    image: "https://images.unsplash.com/photo-1616137422495-1e9e46e2aa77?w=1200&q=80",
    imageAlt: "Sypialnia z naturalnym poliestrowym sufitem, Krzyki, Wrocław",
    surfaceArea: 22,
    year: 2024,
  },
  {
    slug: "salon-poznan-poliester",
    title: "Salon z aneksem",
    citySlug: "poznan",
    city: "Poznań",
    productCategory: "sufit-poliestrowy",
    productLabel: "Sufit poliestrowy",
    spaceType: "salon",
    spaceLabel: "Salon",
    image: "https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=1200&q=80",
    imageAlt: "Salon otwarty na aneks kuchenny z poliestrowym sufitem, Poznań",
    surfaceArea: 52,
    year: 2025,
  },
  {
    slug: "gabinet-lodz-poliester",
    title: "Gabinet domowy",
    citySlug: "lodz",
    city: "Łódź",
    productCategory: "sufit-poliestrowy",
    productLabel: "Sufit poliestrowy",
    spaceType: "salon",
    spaceLabel: "Gabinet",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
    imageAlt: "Gabinet domowy z matowym poliestrowym sufitem, Łódź",
    surfaceArea: 16,
    year: 2024,
  },

  // ════════════════════════════════════════════════════════════
  // Acoustic projects
  // ════════════════════════════════════════════════════════════
  {
    slug: "biuro-warszawa-sluzewiec-akustyka",
    title: "Open-space biuro 320 m²",
    citySlug: "warszawa",
    city: "Warszawa",
    district: "Służewiec",
    productCategory: "sufit-akustyczny",
    productLabel: "Sufit akustyczny",
    spaceType: "biuro",
    spaceLabel: "Open-space biuro",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&q=80",
    imageAlt: "Open-space biuro z akustycznym sufitem napinanym, Służewiec, Warszawa",
    surfaceArea: 320,
    year: 2025,
  },
  {
    slug: "restauracja-krakow-kazimierz-akustyka",
    title: "Restauracja",
    citySlug: "krakow",
    city: "Kraków",
    district: "Kazimierz",
    productCategory: "sufit-akustyczny",
    productLabel: "Sufit akustyczny",
    spaceType: "gastronomia",
    spaceLabel: "Restauracja",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80",
    imageAlt: "Restauracja z akustycznym sufitem na Kazimierzu, Kraków",
    surfaceArea: 95,
    year: 2024,
  },
  {
    slug: "sala-konferencyjna-wroclaw-akustyka",
    title: "Sala konferencyjna",
    citySlug: "wroclaw",
    city: "Wrocław",
    productCategory: "sufit-akustyczny",
    productLabel: "Sufit akustyczny",
    spaceType: "biuro",
    spaceLabel: "Sala konferencyjna",
    image: "https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=1200&q=80",
    imageAlt: "Sala konferencyjna z akustycznym sufitem napinanym, Wrocław",
    surfaceArea: 64,
    year: 2025,
  },
  {
    slug: "kawiarnia-katowice-akustyka",
    title: "Kawiarnia w centrum",
    citySlug: "katowice",
    city: "Katowice",
    productCategory: "sufit-akustyczny",
    productLabel: "Sufit akustyczny",
    spaceType: "gastronomia",
    spaceLabel: "Kawiarnia",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    imageAlt: "Nowoczesna kawiarnia z akustycznym sufitem w centrum Katowic",
    surfaceArea: 78,
    year: 2024,
  },

  // ════════════════════════════════════════════════════════════
  // LED / Light projects
  // ════════════════════════════════════════════════════════════
  {
    slug: "sypialnia-warszawa-ursynow-led",
    title: "Sypialnia z gwiezdnym niebem",
    citySlug: "warszawa",
    city: "Warszawa",
    district: "Ursynów",
    productCategory: "sufit-swietlny",
    productLabel: "Sufit świetlny LED",
    spaceType: "sypialnia",
    spaceLabel: "Sypialnia",
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=80",
    imageAlt: "Sypialnia z sufitem LED w efekcie gwiezdnego nieba, Ursynów, Warszawa",
    surfaceArea: 18,
    year: 2025,
  },
  {
    slug: "lazienka-spa-krakow-led",
    title: "Łazienka SPA",
    citySlug: "krakow",
    city: "Kraków",
    productCategory: "sufit-swietlny",
    productLabel: "Sufit świetlny LED",
    spaceType: "lazienka",
    spaceLabel: "Łazienka SPA",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200&q=80",
    imageAlt: "Łazienka SPA z podświetlanym sufitem LED, Kraków",
    surfaceArea: 14,
    year: 2024,
  },
  {
    slug: "salon-poznan-led-liniowy",
    title: "Salon z liniowym LED",
    citySlug: "poznan",
    city: "Poznań",
    productCategory: "sufit-swietlny",
    productLabel: "Sufit świetlny LED",
    spaceType: "salon",
    spaceLabel: "Salon",
    image: "https://images.unsplash.com/photo-1567016526105-22da7c13161a?w=1200&q=80",
    imageAlt: "Salon z liniowym oświetleniem LED obwodowym, Poznań",
    surfaceArea: 36,
    year: 2025,
  },
  {
    slug: "pokoj-dziecka-warszawa-led-rgb",
    title: "Pokój dziecka z RGB",
    citySlug: "warszawa",
    city: "Warszawa",
    district: "Bielany",
    productCategory: "sufit-swietlny",
    productLabel: "Sufit świetlny LED",
    spaceType: "sypialnia",
    spaceLabel: "Pokój dziecka",
    image: "https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=1200&q=80",
    imageAlt: "Pokój dziecka z kolorowym sufitem LED RGB, Bielany, Warszawa",
    surfaceArea: 16,
    year: 2025,
  },

  // ════════════════════════════════════════════════════════════
  // Photoprint projects
  // ════════════════════════════════════════════════════════════
  {
    slug: "restauracja-warszawa-srodmiescie-fotodruk",
    title: "Restauracja z autorskim drukiem",
    citySlug: "warszawa",
    city: "Warszawa",
    district: "Śródmieście",
    productCategory: "sufit-fotodruk",
    productLabel: "Sufit z fotodrukiem",
    spaceType: "gastronomia",
    spaceLabel: "Restauracja",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
    imageAlt: "Restauracja w Śródmieściu z sufitem z autorskim fotodrukiem, Warszawa",
    surfaceArea: 110,
    year: 2024,
  },
  {
    slug: "pokoj-hotel-czestochowa-fotodruk",
    title: "Pokój hotelowy",
    citySlug: "czestochowa",
    city: "Częstochowa",
    productCategory: "sufit-fotodruk",
    productLabel: "Sufit z fotodrukiem",
    spaceType: "hotel",
    spaceLabel: "Pokój hotelowy",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
    imageAlt: "Pokój hotelowy z artystycznym sufitem fotodruk, Częstochowa",
    surfaceArea: 28,
    year: 2025,
  },
  {
    slug: "sklep-wroclaw-fotodruk-branding",
    title: "Showroom z brandingiem",
    citySlug: "wroclaw",
    city: "Wrocław",
    productCategory: "sufit-fotodruk",
    productLabel: "Sufit z fotodrukiem",
    spaceType: "sklep",
    spaceLabel: "Showroom",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
    imageAlt: "Showroom z brandowanym sufitem fotodruk, Wrocław",
    surfaceArea: 85,
    year: 2024,
  },
  {
    slug: "pokoj-dziecka-poznan-fotodruk",
    title: "Pokój dziecka z motywem nieba",
    citySlug: "poznan",
    city: "Poznań",
    productCategory: "sufit-fotodruk",
    productLabel: "Sufit z fotodrukiem",
    spaceType: "sypialnia",
    spaceLabel: "Pokój dziecka",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
    imageAlt: "Pokój dziecka z sufitem fotodruk w motywie nieba, Poznań",
    surfaceArea: 14,
    year: 2025,
  },

  // ════════════════════════════════════════════════════════════
  // Prefab projects
  // ════════════════════════════════════════════════════════════
  {
    slug: "hotel-gdansk-prefab-seria",
    title: "Hotel · 84 pokoje (prefab)",
    citySlug: "gdansk",
    city: "Gdańsk",
    productCategory: "sufit-prefab",
    productLabel: "Sufit prefabrykowany",
    spaceType: "hotel",
    spaceLabel: "Hotel — seria pokoi",
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80",
    imageAlt: "Hotelowe pokoje z prefabrykowanymi sufitami napinanymi, Gdańsk",
    surfaceArea: 2350,
    year: 2024,
  },
  {
    slug: "deweloper-warszawa-prefab",
    title: "Apartamentowiec · 48 mieszkań",
    citySlug: "warszawa",
    city: "Warszawa",
    productCategory: "sufit-prefab",
    productLabel: "Sufit prefabrykowany",
    spaceType: "salon",
    spaceLabel: "Inwestycja deweloperska",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    imageAlt: "Apartamentowiec z prefabrykowanymi sufitami w 48 mieszkaniach, Warszawa",
    surfaceArea: 1820,
    year: 2025,
  },
  {
    slug: "sklep-siec-katowice-prefab",
    title: "Sieć sklepów · franczyza",
    citySlug: "katowice",
    city: "Katowice",
    productCategory: "sufit-prefab",
    productLabel: "Sufit prefabrykowany",
    spaceType: "sklep",
    spaceLabel: "Sieć handlowa",
    image: "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=1200&q=80",
    imageAlt: "Sklepy sieciowe z jednolitymi prefabrykowanymi sufitami, Katowice",
    surfaceArea: 640,
    year: 2025,
  },
  {
    slug: "moduly-warszawa-prefab-koda",
    title: "Apartamenty modułowe",
    citySlug: "warszawa",
    city: "Warszawa",
    productCategory: "sufit-prefab",
    productLabel: "Sufit prefabrykowany",
    spaceType: "salon",
    spaceLabel: "Budownictwo modułowe",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
    imageAlt: "Apartamenty modułowe z sufitami fabrycznie zamontowanymi, Warszawa",
    surfaceArea: 480,
    year: 2024,
  },
];
