/**
 * JSON-LD schema builders — typed helpers for structured data.
 * File path: /lib/schema.ts
 *
 * One file, one source of truth. Used by metadata generators on each page.
 */

import { siteConfig } from "@/lib/site-config";

/* ─── ORGANIZATION (single business entity) ───────────── */
/**
 * ONE node for the whole company, emitted once from the root layout.
 * It is Organization + LocalBusiness at the same time so that every page
 * can reference it by @id (`/#organization`) instead of emitting its own
 * LocalBusiness copy — 26 "branches" at one Częstochowa address read as
 * fabricated locations, and a self-serving aggregateRating on a business
 * node earns no rich result while inviting a manual action.
 */
export function buildOrganization() {
  const address = {
    "@type": "PostalAddress",
    streetAddress: siteConfig.contact.address.street,
    addressLocality: siteConfig.contact.address.city,
    postalCode: siteConfig.contact.address.postalCode,
    addressRegion: siteConfig.contact.address.region,
    addressCountry: siteConfig.contact.address.country,
  };
  return {
    "@context": "https://schema.org",
    "@type": ["Organization", "LocalBusiness", "HomeAndConstructionBusiness"],
    "@id": `${siteConfig.url}/#organization`,
    name: siteConfig.name,
    legalName: siteConfig.legalName,
    alternateName: ["Alto Design", "Alto Design Sp. z o.o."],
    description: siteConfig.description,
    url: siteConfig.url,
    // /apple-icon is generated by app/apple-icon.tsx — always resolves
    logo: `${siteConfig.url}/apple-icon`,
    image: `${siteConfig.url}${siteConfig.ogImage}`,
    email: siteConfig.contact.email,
    telephone: siteConfig.contact.phonePL,
    foundingDate: "2016",
    founder: { "@type": "Person", name: "Roman Pliuta" },
    taxID: siteConfig.legal.nip,
    vatID: `PL${siteConfig.legal.nip}`,
    identifier: [
      { "@type": "PropertyValue", propertyID: "KRS", value: siteConfig.legal.krs },
      { "@type": "PropertyValue", propertyID: "REGON", value: siteConfig.legal.regon },
    ],
    parentOrganization: {
      "@type": "Organization",
      name: "Stretchgroup",
      url: "https://stretchplafond.be",
    },
    address,
    location: { "@type": "Place", name: "Showroom i fabryka Stretch Sufit", address },
    geo: {
      "@type": "GeoCoordinates",
      latitude: siteConfig.contact.geo.lat,
      longitude: siteConfig.contact.geo.lng,
    },
    hasMap: siteConfig.mapsUrl,
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        opens: "09:00",
        closes: "15:30",
      },
    ],
    priceRange: "$$",
    areaServed: [
      { "@type": "Country", name: "Polska" },
      { "@type": "AdministrativeArea", name: "Województwo śląskie" },
    ],
    sameAs: siteConfig.sameAs,
    contactPoint: [
      {
        "@type": "ContactPoint",
        telephone: siteConfig.contact.phonePL,
        contactType: "customer service",
        areaServed: "PL",
        availableLanguage: ["Polish", "English"],
      },
      {
        "@type": "ContactPoint",
        telephone: siteConfig.contact.phonePLUA,
        contactType: "customer service",
        areaServed: "PL",
        availableLanguage: ["Ukrainian", "Polish"],
      },
    ],
  };
}

/** Reference to the single business node — use instead of inline LocalBusiness copies. */
export const organizationRef = { "@id": `${siteConfig.url}/#organization` };

/* ─── WEBSITE ─────────────────────────────────────────── */
export function buildWebsite() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteConfig.name,
    url: siteConfig.url,
    inLanguage: ["pl-PL", "en", "uk"],
    publisher: organizationRef,
  };
}

/* ─── CITY SERVICE (one per city landing page) ────────── */
/**
 * Replaces the per-city LocalBusiness copies: the provider is the single
 * organization node, the city page describes a Service offered there.
 */
export function buildCityService(opts: {
  /** Absolute URL of the city page (any locale). */
  url: string;
  /** "Sufity napinane w Katowicach" / "Stretch ceilings in Warsaw". */
  name: string;
  serviceType: string;
  description: string;
  /** City name first, then towns served from it. */
  areaServed: string[];
  /** Price floor in PLN per m² (net) — omit to skip the offer. */
  priceFromPLN?: number;
  inLanguage?: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${opts.url}#service`,
    name: opts.name,
    serviceType: opts.serviceType,
    description: opts.description,
    url: opts.url,
    inLanguage: opts.inLanguage ?? "pl-PL",
    provider: organizationRef,
    areaServed: opts.areaServed.map((name) => ({ "@type": "City", name })),
    ...(opts.priceFromPLN && {
      offers: {
        "@type": "Offer",
        priceCurrency: "PLN",
        priceSpecification: {
          "@type": "UnitPriceSpecification",
          minPrice: opts.priceFromPLN,
          priceCurrency: "PLN",
          unitCode: "MTK",
          valueAddedTaxIncluded: false,
        },
        availability: "https://schema.org/InStock",
      },
    }),
  };
}

/* ─── SERVICE ─────────────────────────────────────────── */
export function buildService(opts: {
  name: string;
  description: string;
  slug: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name: opts.name,
    description: opts.description,
    provider: organizationRef,
    url: `${siteConfig.url}/rozwiazania/${opts.slug}`,
    areaServed: "Poland",
  };
}

/* ─── BREADCRUMB LIST ──────────────────────────────────── */
export function buildBreadcrumbs(items: { name: string; url: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

/* ─── FAQ PAGE ─────────────────────────────────────────── */
export function buildFaqPage(faqs: { question: string; answer: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };
}

/* ─── CREATIVE WORK (realizacje case studies) ──────────── */
export type BuildCreativeWorkArgs = {
  name: string;
  description: string;
  url: string;
  image: string[];
  dateCreated: string;
  locationName: string;
  locationCountry: string;
  contributor?: { name: string; url: string };
  producer: { name: string; url: string };
  keywords: string[];
};

export function buildCreativeWork(args: BuildCreativeWorkArgs) {
  return {
    "@context": "https://schema.org",
    "@type": ["CreativeWork", "Project"],
    name: args.name,
    description: args.description,
    url: args.url,
    image: args.image,
    dateCreated: args.dateCreated,
    locationCreated: {
      "@type": "Place",
      name: args.locationName,
      address: {
        "@type": "PostalAddress",
        addressLocality:
          args.locationName.split(",")[1]?.trim() ?? args.locationName,
        addressCountry: args.locationCountry,
      },
    },
    ...(args.contributor && {
      contributor: {
        "@type": "Organization",
        name: args.contributor.name,
        url: args.contributor.url,
      },
    }),
    producer: {
      "@type": "Organization",
      name: args.producer.name,
      url: args.producer.url,
    },
    keywords: args.keywords.join(", "),
  };
}
